title: "Sundaresh Iyer"
description: "Data Science Portfolio"
url: "https://iyers.github.io/sundareshiyer.github.io"
baseurl: "https://iyers.github.io/sundareshiyer.github.io"

# Social links
linkedin_username: sundaresh-iyer
github_username: sundareshiyer

# Build settings
markdown: kramdown
permalink: /:title/

# Include custom directories
include: ['_pages']
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
