title: "Sundaresh Iyer"
description: "Portfolio of Work"
excerpt: "Hi! I'm a Business Analyst and a Data Scientist. This portfolio webpage showcases different projects and responsibilities Ive held during my professional years and some data science projects I've done to show specific programming skills. Please visit LinkedIn page to connect with me or download my Resume by using the links below!"
url: "https://iyers.github.io"
baseurl: "/sundareshiyer.github.io"

# Social links
linkedin_username: sundaresh-iyer
github_username: IyerS

# Build settings
markdown: kramdown
permalink: /:title/

# Include custom directories
include: 
  - _pages
  - assets
sass:
  sass_dir: _sass
  style: compressed


# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
