title: "Sundaresh Iyer"
description: "Data Science Portfolio"
excerpt: "Hi, I'm Sundaresh, a Data Scientist and Business Analyst. My portfolio showcases interesting data science projects I've undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
url: "https://iyers.github.io"
baseurl: "/sundareshiyer.github.io"

# Social links
linkedin_username: sundaresh-iyer
github_username: IyerS

# Build settings
markdown: kramdown
permalink: /:title/

# Include custom directories
include: ['_pages']
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
